### ISSUE TITLE
[feature] set scrolling element

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-list#23]
Currently `<virtual-list>` supports only the main document as scrolling element. Ideally we'd want to allow the user to setup another scrolling element.

We could check the css `overflow` property of the container, and if it is `scroll` or `auto` then the container is the scrolling element

**Comment by domenic** [comment]
My take is that the virtual-list itself should be the scrolling element. So if I want something like https://bvaughn.github.io/react-virtualized/#/components/List I would do

```js
<virtual-list style="height: 300px;"></virtual-list>
```

whereas if I wanted the whole document I would do

```js
<virtual-list style="100vh"></virtual-list>
```

**Comment by valdrinkoshi** [comment]
Agreed. VirtualList can be "smart" and check which element is the scrolling one by traversing the parents until finding the one that qualifies, something like this maybe?
```js
const isScrollElement = el.offsetHeight > 0 &&
                        getComputedStyle(el).overflow !== 'visible';
```

**Comment by valdrinkoshi** [comment]
In order to have another scrolling element we'd need a wrapper with a `height` and `overflow` setup, and a container with a bigger height compared to the wrapper:
```html
<div id="wrapper" style="height: 300px; overflow: auto">
  <div id="container" style="height: 600px"> content here! </div>
</div>
```

In `RepeatsAndScrolls` mixin we'd be finding the scrolling parent and listen for `scroll` events on it, and we'd still need to set the `min-height` on the `container`.

For `<virtual-list>` we can:
(1) host the "container" element in its shadowRoot and make it be the actual `container`
```html
<virtual-list>
  #shadowRoot
    <div id="container">
       children appended here
   </div>
  #/shadowRoot
</virtual-list>
```
The drawback is that the stamped children cannot be styled as they'll be scoped to the virtual-list shadowRoot styling scope. e.g. this wont work
```html
<style> section { color: red} </style>
<virtual-list id=list></virtual-list>
<script>
  list.items = new Array(10);
  list.newChild = () => {
    const child = document.createElement('section');
    child.textContent = 'hello';
    return child;
  };
</script>
```

(2) request the user to wrap the `<virtual-list>` with a sized element 
```html
<div id="wrapper" style="height: 300px; overflow: auto">
  <virtual-list>
    #shadowRoot
      <slot></slot>
    #/shadowRoot
  </virtual-list>
</div>
```
With this option, the user can style the children as they'd be stamped in the same styling scope as virtual-list.

**Comment by domenic** [comment]
(1) seems really nice if we could fix the styling issue. What about if you put a slot inside the container, so that the children were actually in the light DOM?
