### ISSUE TITLE
Type of items property

### ISSUE THREAD

**Issue by domenic** [valdrinkoshi/virtual-list#29]
Right now the `items` setter just takes whatever its given and stores it. The getter returns the stored value.

The more web-platformey thing to do would be:

- The setter accepts any iterable, snapshotting that iterable at the time it's set
- The getter returns a frozen array of the snapshot

The main benefit here is that you can't write code like

```js
list.items.push(...);
```

because the array is frozen. (Such code won't work, because there's no notification that the array changed. You'd instead need to use `requestReset()`: see #26.)

The drawback of this is that it's O(n) in the total number of items. The current requestReset() pattern allows O(1) item additions and removals.

Not sure what to do here, but I wanted to have a tracking issue open.

**Comment by valdrinkoshi** [comment]
Closing this as now we expose `totalItems: number` instead of `items: array` - see #65
