### ISSUE TITLE
[feature] expose itemKey function

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-list#32]
The `Repeats` mixin keeps track of the created DOM in the key/child map `_keyToChild`. When a child is not found, it will invoke `newChild` to create it and stores it in the `_keyToChild` map.
In this example `newChild` is invoked only for the newly added item, while `updateChild` is invoked for all the items:
```js
list.items = list.items.concat({name: 'new item'});
```

`_keyToChild` uses index as the key. This can be customized by providing the `itemKey` function to return a custom key `itemKey(item: any) => string|number`

Should we expose this property in `<virtual-list>`?

**Comment by domenic** [comment]
Am I understanding correctly that currently the default `itemKey` implementation is basically `items.indexOf(item)`?

This seems quite related to #21; if we change to use the interface there we'd probably want to expose `itemKey`.

What new use cases would exposing this open up? Here is one guess; please tell me if it's right: if you had a contact list, and did `itemKey(contact) { return contact.userId; }`, then you could do something like

```js
function moveContactToEnd(contact) {
  myContacts.splice(myContacts.indexOf(contact), 1); // remove it
  myContacts.push(contact); // add it to the end
  virtualList.items = myContacts;
}
```

With the default itemKey, this would call newChild, even though it was the same contact. Whereas for the customized itemKey, this would not call newChild; it would just reuse the same DOM element.

Is that right?

**Comment by valdrinkoshi** [comment]
All of the above is correct. Basically `itemKey` would be a mean to have a more efficient re-ordering.

Re #21: I think this is tangential, as it would change the signature of the method, but not the functionality:
```js
// Current, with `items`
itemKey(contact) { return contact.userId; } 

// Proposal #21, with `totalItems`
itemKey(index) { return myContacts[index].userId; }
```

**Comment by domenic** [comment]
Hmm, I suppose you are right; I didn't realize it would be that simple of a change.

I support exposing this, with good documentation for when you would use it.

**Comment by valdrinkoshi** [comment]
Writing this scenario down for my own sanity & help preparing the demo.

Simplifying the contacts example above, imagine `myContacts` contains only 3 contacts, all visible:
```js
const myContacts = [{name: 'Val'}, {name: 'Dom'}, {name: 'Gray'}];
virtualList.items = myContacts;
virtualList.newChild = (contact) => {
  const div = document.createElement('div');
  div.textContent = contact.name;
  return div;
};
```
This renders the 3 contacts, and the `<virtual-list>` key/Element map is:
```
0: <div>Val</div>
1: <div>Dom</div>
2: <div>Gray</div> 
```
Then, we run:
```js
moveContactToEnd('val');
```

This will not render correctly, because `newChild` is never called. To fix this, the user could just use `updateChild`, or use `itemKey`.
- `updateChild` would update 2 DOM nodes
- `itemKey` would move 1 DOM node to the bottom

This gives more options to the user:
- when data contents (each contact object) will not change, it makes sense to use `newChild + itemKey`
- when data contents changes, it might be faster to use `newChild + updateChild`
