### ISSUE TITLE
https://valdrinkoshi.github.io/virtual-list/components/virtual-list/demo/ ❌

### ISSUE THREAD

**Issue by chinanf-boy** [valdrinkoshi/virtual-list#34]
## browser
`Firefox develop lastest`

## console

```  js
SyntaxError: expected expression, got keyword 'import'[详细了解]
virtual-list-element.js:20:26
```

**Comment by valdrinkoshi** [comment]
We use dynamic import() to lazily load some resources, this is currently supported in Chrome and Safari Technology Preview https://developers.google.com/web/updates/2017/11/dynamic-import

**Comment by chinanf-boy** [comment]
O-O, 😯 I got this, 😊
