### ISSUE TITLE
Let's discuss microtask-batched reading of items array

### ISSUE THREAD

**Issue by domenic** [valdrinkoshi/virtual-list#51]
Per https://github.com/valdrinkoshi/virtual-list/pull/48#discussion_r185677707, apparently virtual-list only reads from the items array after a microtask delay. This is pretty unusual, and I think we should discuss it.

In particular, the example discussed there is pretty confusing. Consider a list where you have only set `newChild`. If you do

```js
// (1)
list.items = x;
list.items = y;
```

then it will call `newChild` for all the items in y. But if you do

```js
// (2)
list.items = x;
setTimeout(() => {
  list.items = y;
}, 0);
```

Then it will call `newChild` for all the items in x, and the items in y are ignored. I would prefer that both are consistent: i.e. both do newChild for all items in x.

Now consider a list where you have set both `newChild` and `updateChild`. Then (1) will call newChild + updateChild for all the items in y, and (2) will call newChild for all the items in x, and updateChild for all the items in y. I would prefer that both are consistent: i.e. both do newChild for all items in x, and updateChild for all items in y.

---

Note that the platform has some precedent for delayed rendering. `img.src = x; img.src = y;` will only try to load y. This case feels worse because of the newChild/updateChild distinction, though.

MutationObservers are also microtask-batched, but they don't do coalescing, so they tell you *all* the things that happened since the last time, not just the latest thing.

---

I'm open to being convinced that batching is more important than consistency. But I lean toward saying that if developers change `items` a lot, they should know that will cause a lot of updates, and we shouldn't try to batch for them.

Maybe if developers want batching, we should have something more suited to their use case, e.g.

```js
const resumeUpdates = list.suspendUpdates();
... mutate list.items a lot ...
resumeUpdates();
```

Also, if we do think batching is important, I think microtask batching is probably not right, and we should do requestAnimationFrame batching instead.

Thoughts?

**Comment by ojanvafai** [comment]
My first thought is that requestAnimationFrame batching makes sense. I don't think authors will understand that setting list.items multiple times to result in a huge cascade of work and will thus stumble across performance problems easily if we don't do any batching. Agree that microtask batching probably isn't the right batching to do.

**Comment by ojanvafai** [comment]
Thinking more about why I don't think authors would understand the perf implications of the non-batched version: setting a property feels cheap, so people will treat it as cheap and need high expertise to do the batching themselves or rely on a framework to do it for them.

**Comment by domenic** [comment]
OK, thanks for the background. I guess I am on board with batching. But I think some number like 6 microtasks doesn't have a place in a web standard.

I would suggest moving us toward an architecture where everything happens synchronously, except at one point in the code we use requestAnimationFrame batching. Instead of having six points in the code all of which use microtask batching.

So for example in the above code I would envision that both setters do:

```js
if (!this._handle) {
  this._handle = requestAnimationFrame(() => {
    this._handle = null;
    doAllTheStepsSync();
  });
```

Does that seem feasible?

**Comment by valdrinkoshi** [comment]
Additionally, should the user have expectations as to "when" the virtual-list renders? After all, the list needs to be sized by the user, `updateChild` could be seen as a signal as to when the child has been added to the DOM, and `rangechange` could be seen as the signal when all items have been rendered.

**Comment by domenic** [comment]
> as there are a couple back-n-forwards between VirtualList and Layout to figure out sizes and positions.

In that case, I'd suggest doing all of them synchronously, in a single batch, like my above code.

> Doing rendering, positioning and measurement in separate microtasks actually helps playing nice with browser timing and avoids forcing layout, while still being executed before the next frame.

I think my above code would also accomplish this.

> Can we leave this as an implementation detail, but require batching to be executed within 1 RAF time (doesn't matter how the internal implementation handles it)?

This might be OK as a fallback, but it's not something I'm very comfortable with in a platform API. We should instead use well-defined timing for when updates are visible. I think requestAnimationFrame timing is a good time for that.

> Additionally, should the user have expectations as to "when" the virtual-list renders?

In general, it's important to get predictability and interop for when rendering happens. The `<input>` control would not be very useful if changing its `value` took an unspecified amount of time to render or reflect to the DOM, and you had to listen for `"change"` to find out when that happened.

**Comment by valdrinkoshi** [comment]
The current implementation does respect the RAF timing

demo: http://output.jsbin.com/dojabed/1/quiet
code: http://jsbin.com/dojabed/1/edit?html,output
<img width="310" alt="screen shot 2018-05-08 at 5 06 41 pm" src="https://user-images.githubusercontent.com/6173664/39789086-9ab7d108-52e2-11e8-95d6-869f922242a5.png">
Note that the first time the RAF timing is not respected because we lazy-load the Layout class (currently discussing about this in #60).

**Comment by domenic** [comment]
That doesn't seem like it's lined up with the RAF timing; it's often 6-9 milliseconds off? So it's rendering too often, from what I can tell.

**Comment by valdrinkoshi** [comment]
oh sorry i forgot to specify that in that demo I clicked "go" 5 times, so I got 5 renderings (just to have an average).
The virtual-list rendering is done before a RAF, so children are measured and positioned before we paint (no visible glitches)

**Comment by domenic** [comment]
Note that you don't want to render before rAF time; that's wasted work. You want to render at rAF time, since rAF time is right before the browser's painting time.

**Comment by valdrinkoshi** [comment]
Yeah, I just wanted to verify that we're staying within the rAF timing 😁 

I don't think we can have a single batch. If we wait 1 rAF before applying the changes, we'll be forcing layout when we append new children and measure them right after.

For the `Layout` batching, it was designed to be compatible with Web Workers. We never got to experiment more with this, but in a scenario where we put `Layout` in a Web Worker we wouldn't be able to force sync execution.
