### ISSUE TITLE
Consider not loading layouts dynamically?

### ISSUE THREAD

**Issue by domenic** [valdrinkoshi/virtual-list#60]
Right now the code loads layouts dynamically. I'm not sure that makes much sense for something that would be bundled with the browser.

But maybe it does? After all, you still pay some cost for loading the layouts in to memory, and maybe you should only pay those costs for layouts you use. I'm not sure.

From a spec perspective, I guess the impact of loading layouts lazily is that we'd have to mandate in the spec that changing the layout can take an arbitrarily long time to apply (e.g. if loading them takes longer than one animation frame). That seems a bit bad.

**Comment by valdrinkoshi** [comment]
Loading the Layout classes lazily slows the initialization of at least couple microtasks, which is not ideal.
We could ship 2 custom elements, `<virtual-list>` and `<virtual-grid>`, each with a boolean property `horizontal`
```html
<virtual-list></virtual-list>
<virtual-list horizontal></virtual-list>

<virtual-grid></virtual-grid>
<virtual-grid horizontal></virtual-grid>
```

**Comment by domenic** [comment]
Um, it slows it down for arbitrarily long, right? Since it depends on how long the user's disk takes to load a file.

The two-elements idea is really interesting. I can see arguments in both directions. What would make it really obvious is if there were different API surfaces between the grid and the list; so far we don't have any, but maybe some exist.

**Comment by valdrinkoshi** [comment]
Both layouts load layout-1d-base.js which contains most of the logic. I think it's fine for now to synchronously load both layouts. We can refactor the code on a later moment to bring back dynamic layout class loading, or just change the `layout` property to accept a Layout instance.
