### ISSUE TITLE
rename <virtual-list> to <virtual-scroller>

### ISSUE THREAD

**Issue by valdrinkoshi** [valdrinkoshi/virtual-list#72]
`<virtual-scroller>` is the thing that needs to be sized and creates DOM as the user scrolls to it

`<virtual-content>` is the thing that auto-sizes itself according to the estimated size of the items, and creates DOM only for the visible portion of it (can be contained in any scroll container).

**Comment by domenic** [comment]
And to be clear, `<virtual-content>` is not yet documented or exposed, although we might want to do that in the future.
